server:
  port: 8183

logging:
  level:
    com.spring.food.ordering.system: DEBUG

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=restaurant&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
  sql:
    init:
      mode: ALWAYS
      platform: postgres
      schema-locations: classpath:init-schema.sql
      data-locations: classpath:init-data.sql