version: '3.7'
services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - "./volumes/kafkaui/config.yml:/etc/kafkaui/config.yml"
    networks:
      - ${GLOBAL_NETWORK:-kafka}