services:
  postgres:
    image: quay.io/debezium/example-postgres
    container_name: postgres
    ports:
      - 5433:5432
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "max_replication_slots=4"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=4"
      - "-c"
      - "log_min_error_statement=fatal"
      - "-c"
      - "listen_addresses=*"
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    networks:
      - ${GLOBAL_NETWORK:-kafka}
